# Generated by Django 3.2 on 2021-04-15 20:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Cred_Task_Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
