# Generated by Django 3.2 on 2021-04-15 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cred_Task_Api', '0002_movies_movie_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name_plural': 'Collection'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name_plural': 'Movie'},
        ),
        migrations.AlterField(
            model_name='movies',
            name='collection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_list', to='Cred_Task_Api.collection'),
        ),
    ]
