# Generated by Django 3.2 on 2021-04-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cred_Task_Api', '0003_auto_20210416_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_request', models.IntegerField()),
            ],
        ),
    ]
