# Generated by Django 3.2 on 2021-04-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cred_Task_Api', '0004_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='counter_name',
            field=models.CharField(default='Counter', max_length=10),
        ),
        migrations.AlterField(
            model_name='counter',
            name='number_of_request',
            field=models.IntegerField(default=0),
        ),
    ]
